#ifndef CONFIG_H
#define CONFIG_H

#define CAMERA_DEVICE_NUMBER 0
#define MOTION_DETECTION_MIN_AREA 600
#define MOTION_DETECTION_NOISE 21
#define MOITON_DETECTION_FRAME_MOTION_DEFAULT 2

#define MQTT_KEEP_ALIVE_INTERVAL_SEC 20
#define MQTT_ONLINE_PREFIX "/online"
#define MQTT_IMAGE_PREFIX "/image"
#define MQTT_VIDEO_PREFIX "/video"
#define MQTT_SOUND_PREFIX "/sound"
#define MQTT_SETTINGS_PREFIX "/settings"
#define MQTT_CONTROL_PREFIX "/control"
#define MQTT_SYSTEM_STATE_PREFIX "/state"
#define MQTT_ONLINE_MESSAGE "YES"
#define MQTT_OFFLINE_MESSAGE "NO"
#define MQTT_CONTROL_ON_MESSAGE "ON"
#define MQTT_CONTROL_OFF_MESSAGE "OFF"
#define MQTT_CONTROL_POWER_OFF_MESSAGE "POWER_OFF"
#define MQTT_STATE_RUNNING_MESSAGE "RUNNING"
#define MQTT_STATE_STOPPED_MESSAGE "STOPPED"

#define MQTT_DATA_PACKET_LENGTH 65536   // 64 KB

#define GPIO_READING_INTERVAL_MS 1000
#define WIFI_BUTTON_PRESS_ACTIVATE_TIME_MS 5000
#define WIFI_BUTTON_PIN_NUMBER 26
#define WIFI_INDICATOR_PIN_NUMBER 13
#define MQTT_INDICATOR_PIN_NUMBER 19
#define WIFI_DHCPCD_CONFIGURATION_FILE_NAME "/etc/dhcpcd.conf"
#define WIFI_DNSMASQ_CONFIGURATION_FILE_NAME "/etc/dnsmasq.conf"
#define WIFI_HOSTAPD_CONFIGURATION_FILE_NAME "/etc/hostapd.conf"
#define WIFI_HOSTAPD_MAIN_FILE_NAME "/etc/default/hostapd"

#define X_RES_DEFAULT 640
#define Y_RES_DEFAULT 480
#define FPS_DEFAULT 5
#define CAPTURE_TYPE_DEFAULT 0  // IMAGE_CAPTURE
#define FRAMES_TRIGGER_DEFAULT 3
#define IMAGE_TIME_DIFF_DEFAULT 2
#define SEC_TO_STOP_DEFAULT 1
#define SHOW_TIME_DEFAULT true
#define VIDEO_LENGTH_DEFAULT 10

#define MQTT_HOST_NAME_DEFAULT "136.144.216.100"
#define MQTT_PORT_DEFAULT 1883
#define MQTT_USER_NAME_DEFAULT "mikroelectron"
#define MQTT_PASSWORD_DEFAULT "abcdABCD1234"
#define MQTT_TOPIC_DEFAULT "wicam"

#define SOUND_RECORDER_DEVICE "" // Default for system
#define SOUND_RECORDER_CODEC "audio/x-vorbis" // Default for format
#define SOUND_RECORDER_SAMPLE_RATE 0 // Default for format
#define SOUND_RECORDER_CHANNEL_COUNT -1 // Default
#define SOUND_RECORDER_QUALITY  2 // quality from (0 - 4) we need normal quality
#define SOUND_RECORDER_CONTAINER "audio/ogg"  // Get it from file name extension

#define SETTINGS_FILENAME "settings.ini"
#endif // CONFIG_H

